DynamoDB:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.DYNAMO_DB_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: original_name
        AttributeType: S
      - AttributeName: creation_date
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    GlobalSecondaryIndexes:
      - IndexName: nameAndDate
        KeySchema:
          - AttributeName: original_name
            KeyType: HASH
          - AttributeName: creation_date
            KeyType: RANGE
        Projection:
          ProjectionType: ALL