DynamoDB:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.DYNAMO_DB_TABLE}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: userId
        AttributeType: S
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: userId
        KeyType: HASH
      - AttributeName: id
        KeyType: RANGE
    # GlobalSecondaryIndexes:
    #   - IndexName: uploadStatusAndUserId
    #     KeySchema:
    #       - AttributeName: userId
    #         KeyType: HASH
    #       - AttributeName: uploadStatus
    #         KeyType: RANGE
    #     Projection:
    #       ProjectionType: ALL
    # For this demo we ae using a TTL so that our records expire after 1 day. 
    TimeToLiveSpecification:
      AttributeName: TimeToLive
      Enabled: true